name: React build
on: 
  push: 
    branches:
      - fe-main
  pull_request:
    branches:
      - fe-main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code.
        uses: actions/checkout@main

      - name: Cache node modules 
        uses: actions/cache@v1
        with:
          path: FE-MyCarMaster/node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install Dependencies
        run: cd ./FE-MyCarMaster && npm install

      - name: Build
        run: cd ./FE-MyCarMaster && npm run build 

      - name: Deploy 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.FE_AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.FE_AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            dist s3://h5-front-bucket
